version: '3'

volumes:
  static-files-peopleportal:


services:

  postgresdb:
    image: postgres:latest
#    volumes:
#      - ./dockers/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_DB=peopleportal
      - POSTGRES_PASSWORD=postgrespass

  djangoapp:
    depends_on:
      - postgresdb
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - static-files-peopleportal:/app/staticfiles
    environment:
       - PP_SECRET_KEY=+3ji@o8^0mxm81k&lh_&wgmqil=keb)hs)i#!+wplpm199z@xn
       - PP_DEBUG=1
       - PP_PG_HOST=postgresdb
       - PP_PG_PORT=5432
       - PP_PG_USERNAME=postgres
       - PP_PG_PASSWORD=postgrespass
       - PP_PG_DBNAME=peopleportal

  nginx:
    depends_on:
      - djangoapp
      - postgresdb
    build:
      context: ./dockers/nginx
      dockerfile: Dockerfile
    volumes:
      - static-files-peopleportal:/app/static-files-peopleportal
    restart: always
    ports:
      - '9000:80'