apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-staticfiles
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi  # Edit: Change this as per your requirement