apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-postgresdb-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi  # Edit: Change this as per your requirement