# Generated by Django 3.1.2 on 2020-10-27 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Employee', 'verbose_name_plural': 'Employees'},
        ),
        migrations.AlterField(
            model_name='employee',
            name='team',
            field=models.ForeignKey(blank=True, help_text='Team in which this employee belongs to.', null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.team'),
        ),
    ]
