# Generated by Django 3.1.2 on 2020-10-28 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201027_2306'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='permission',
            unique_together={('resource', 'code')},
        ),
    ]
