# Generated by Django 3.1.2 on 2020-10-30 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conferenceroom',
            options={'ordering': ('room_id',)},
        ),
    ]
